#!/bin/bash

# Start NRL list mode and let it run for an
# indefinite amount of time.
# Health data also starts to collect.
# Note that the Bridgeport detectors have a bug that
# their USB connections fail under certain conditions
# after an extended period of time.
# So if you set this to free-run for several hours,
# it will likely not work.
# A more surefire approach would be to set this running,
# and then every ~30min or so, restart data acquisition by
# automatically re-running the script.

bash ../check_running.bash || exit 1

# For health port and UDP device
source ../udpcap_ports.bash

echo "wake" > $det_udp_dev

# Health packets every 10s
echo "start-periodic-health 10 127.0.0.1:$DET_HEALTH_PORT" > $det_udp_dev

# Start real data acquisition
echo "start-nrl-list" > $det_udp_dev
